<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('http://farm9.staticflickr.com/8241/8584627345_59b373e901_o.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>Phalcon test</h1>
                    <hr class="small">
                    <span class="subheading">A Clean Blog Theme by Start Bootstrap</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

<?php foreach ($posts as $postId => $postData) : ?>
            <div class="post-preview">
                <a href="<?=$this->url->get(array('for' => 'blog-post-view', 'post_id' => $postId))?>">
                    <h2 class="post-title">
                        <?=$postData['title']?>
                    </h2>
                    <h3 class="post-subtitle">
                        <?=$postData['lead']?>
                    </h3>
                </a>
                <p class="post-meta"><?=$postData['public_date']?></p>
            </div>
            <hr>
<?php endforeach; ?>

        </div>
    </div>
</div>
