<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('https://farm4.staticflickr.com/3560/5830241773_b0fa67a6d3_o.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-heading">
                    <h1>postId: <?=$postId?></h1>
                    <h2 class="subheading">postId: <?=$postId?></h2>
                    <span class="meta">August 24, 2014</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Post Content -->
<article>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>postId: <?=$postId?></p>

                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eu nulla id elit accumsan volutpat. Nulla lacinia tellus ac suscipit pretium. Morbi risus tortor, eleifend vitae laoreet fermentum, efficitur nec tortor. Donec et libero vitae felis sollicitudin tempus sit amet ut felis. Nullam luctus, odio id vehicula gravida, sem nunc maximus urna, vitae molestie orci ex viverra sem. Proin imperdiet lectus urna. Cras congue fringilla nibh, vitae vulputate mauris elementum non. Maecenas aliquam imperdiet aliquam. Cras at tempus nibh. Sed placerat lorem sagittis accumsan feugiat. Duis aliquet interdum aliquet. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p>

                <p>Suspendisse vel pharetra enim, imperdiet tincidunt est. Duis vestibulum ligula vel lacus pulvinar aliquam. Proin eget enim at augue pulvinar ornare at ac enim. Cras tincidunt sollicitudin odio ut egestas. Morbi id lacinia ligula, vitae mollis nunc. Donec quis risus id nisi gravida imperdiet nec imperdiet orci. Curabitur in laoreet tellus. Donec venenatis et leo non vulputate. Aenean quis lacus et metus porta ornare nec vitae sem. Morbi dignissim interdum efficitur.</p>

                <p>Cras vel dignissim sem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque eget dignissim libero. Pellentesque massa justo, consequat malesuada mi sed, lacinia mattis dui. Curabitur sodales eu justo et consequat. Aliquam erat volutpat. Proin leo metus, dignissim in sodales quis, volutpat ac orci. Fusce rhoncus nunc ut ornare porta. Curabitur dapibus arcu non est scelerisque elementum. Curabitur ipsum arcu, tempor ut erat bibendum, dapibus cursus lorem.</p>

                <p>Phasellus convallis urna nec eros hendrerit tincidunt. Ut cursus massa erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse ultrices facilisis lacus. Donec accumsan vulputate dui ac mattis. Curabitur tincidunt feugiat elementum. Aliquam suscipit augue mauris, sit amet faucibus magna auctor ut. Proin egestas turpis lobortis ullamcorper convallis. Nunc nec sapien dictum, rutrum erat interdum, laoreet magna. Quisque fringilla nisi nec nunc maximus facilisis. Suspendisse tristique tellus sed dui placerat tempus.</p>

                <p>Quisque a enim ut orci convallis iaculis non ut felis. Cras fermentum dui venenatis lacus pellentesque feugiat. Ut cursus sagittis porta. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque condimentum justo ac venenatis porta. Duis semper tincidunt suscipit. Pellentesque eu ornare leo, non congue lectus. Cras et dapibus ex. Suspendisse finibus est sit amet mi efficitur rhoncus et vel eros. Nullam dignissim blandit fermentum. Cras vestibulum rutrum cursus.</p>
            </div>
        </div>
    </div>
</article>