<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('https://farm4.staticflickr.com/3560/5830241773_b0fa67a6d3_o.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-heading">
                    <h1><?=$post['title']?></h1>
                    <!--<h2 class="subheading">&nbsp;</h2>-->
                    <span class="meta"><?=$post['public_date']?></span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Post Content -->
<article>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p><strong><?=$post['lead']?></strong></p>
                <p><?=$post['content']?></p>
            </div>
        </div>
    </div>
</article>
