DROP TABLE IF EXISTS `blog_posts`;

CREATE TABLE `blog_posts` (
  `id` int(100) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `lead` text NOT NULL,
  `content` text NOT NULL,
  `public_date` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `blog_posts` ( `title`, `lead`, `content`, `public_date`) VALUES
(
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
  'Suspendisse justo neque, mollis sed tincidunt non, hendrerit mollis elit. Curabitur maximus ex erat, nec lobortis nisl aliquam id. Sed velit odio, mollis nec arcu a, lobortis finibus ante. Vestibulum mollis sem eget elit scelerisque posuere. Fusce pharetra feugiat ante sed venenatis. Nullam volutpat, nunc in eleifend tincidunt, ex dui fermentum ipsum, non cursus nisl erat a augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
  '<p>Sed volutpat libero ac velit sollicitudin lacinia. Proin justo diam, ullamcorper at sagittis vitae, suscipit id nunc. Integer tincidunt varius justo. Suspendisse accumsan sapien at tincidunt venenatis. Nam non ligula ligula. Maecenas vel dui efficitur, dictum turpis eu, iaculis odio. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam iaculis sollicitudin turpis, vel scelerisque ante varius in. Nulla porttitor tempus magna. Suspendisse ac pretium dui, ac dapibus massa. Aliquam in egestas arcu, a consectetur ipsum. Mauris vitae tellus ut neque mollis rutrum. Nulla placerat fermentum quam, sed viverra enim volutpat nec. Fusce tincidunt tempus mauris, nec imperdiet erat luctus vitae. Quisque hendrerit quis purus nec sodalesz</p>
  <p>Praesent facilisis quis dui non iaculis. Sed ut odio vitae odio maximus convallis ac ut orci. Nam vel leo vehicula, pretium magna quis, rutrum dui. Donec mollis eleifend nunc in lacinia. Donec feugiat gravida ex, consectetur imperdiet tellus lacinia at. Vestibulum maximus erat odio, ut sagittis ipsum varius convallis. Nam pulvinar odio odio, in rhoncus lorem egestas ultricies. Proin faucibus diam vel sagittis facilisis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tincidunt nulla vel odio iaculis aliquet. Cras eget efficitur sapien. Duis aliquet id nunc at imperdiet. Proin ut rutrum justo. Duis dui neque, tristique eu luctus in, volutpat at dolor.</p>
  <p>Ut efficitur nunc eget laoreet feugiat. Nunc mattis eleifend risus, eget placerat magna dictum ac. Morbi volutpat fringilla ex, non varius ante interdum ac. Vivamus vitae ante sit amet nunc facilisis tempus. Praesent rutrum euismod mi, et elementum purus gravida id. Sed placerat rhoncus interdum. Nunc vel nisi non tortor finibus imperdiet. Aliquam erat volutpat. Sed commodo velit lorem, id pulvinar ipsum dignissim non. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce vitae nisi nec erat sodales luctus ut vitae felis. Quisque id lacinia lacus. In vehicula libero enim, et ullamcorper justo commodo et. Cras blandit sodales ultricies.</p>
  <p>Aliquam erat volutpat. Aenean sed gravida purus. Donec egestas massa at diam tempus faucibus. Phasellus id neque suscipit, luctus dolor id, vestibulum lorem. Integer dignissim sem sed arcu maximus pulvinar. Vivamus ultrices viverra efficitur. Mauris vitae dignissim ante, sed tincidunt neque. Curabitur mattis mollis pellentesque.</p>',
  '2015-06-09 12:30'
),
(
  'Pellentesque interdum faucibus velit id ullamcorper',
  'Usce dictum ligula odio, nec egestas neque dignissim vel. Integer orci felis, egestas ut feugiat vitae, suscipit eu ipsum. Pellentesque efficitur, nibh non hendrerit commodo, dui erat dictum purus, vel mollis nisi magna at augue. Vestibulum posuere sit amet risus semper aliquet. Mauris interdum nunc id est cursus, non varius ex luctus.',
  '<p>Sed volutpat libero ac velit sollicitudin lacinia. Proin justo diam, ullamcorper at sagittis vitae, suscipit id nunc. Integer tincidunt varius justo. Suspendisse accumsan sapien at tincidunt venenatis. Nam non ligula ligula. Maecenas vel dui efficitur, dictum turpis eu, iaculis odio. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam iaculis sollicitudin turpis, vel scelerisque ante varius in. Nulla porttitor tempus magna. Suspendisse ac pretium dui, ac dapibus massa. Aliquam in egestas arcu, a consectetur ipsum. Mauris vitae tellus ut neque mollis rutrum. Nulla placerat fermentum quam, sed viverra enim volutpat nec. Fusce tincidunt tempus mauris, nec imperdiet erat luctus vitae. Quisque hendrerit quis purus nec sodalesz</p>
  <p>Praesent facilisis quis dui non iaculis. Sed ut odio vitae odio maximus convallis ac ut orci. Nam vel leo vehicula, pretium magna quis, rutrum dui. Donec mollis eleifend nunc in lacinia. Donec feugiat gravida ex, consectetur imperdiet tellus lacinia at. Vestibulum maximus erat odio, ut sagittis ipsum varius convallis. Nam pulvinar odio odio, in rhoncus lorem egestas ultricies. Proin faucibus diam vel sagittis facilisis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tincidunt nulla vel odio iaculis aliquet. Cras eget efficitur sapien. Duis aliquet id nunc at imperdiet. Proin ut rutrum justo. Duis dui neque, tristique eu luctus in, volutpat at dolor.</p>
  <p>Ut efficitur nunc eget laoreet feugiat. Nunc mattis eleifend risus, eget placerat magna dictum ac. Morbi volutpat fringilla ex, non varius ante interdum ac. Vivamus vitae ante sit amet nunc facilisis tempus. Praesent rutrum euismod mi, et elementum purus gravida id. Sed placerat rhoncus interdum. Nunc vel nisi non tortor finibus imperdiet. Aliquam erat volutpat. Sed commodo velit lorem, id pulvinar ipsum dignissim non. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce vitae nisi nec erat sodales luctus ut vitae felis. Quisque id lacinia lacus. In vehicula libero enim, et ullamcorper justo commodo et. Cras blandit sodales ultricies.</p>
  <p>Aliquam erat volutpat. Aenean sed gravida purus. Donec egestas massa at diam tempus faucibus. Phasellus id neque suscipit, luctus dolor id, vestibulum lorem. Integer dignissim sem sed arcu maximus pulvinar. Vivamus ultrices viverra efficitur. Mauris vitae dignissim ante, sed tincidunt neque. Curabitur mattis mollis pellentesque.</p>',
  '2015-06-10 13:30'
),
(
  'Interdum et malesuada fames ac ante ipsum primis in faucibus',
  'Donec mattis risus vel ante viverra cursus. Integer orci ex, vehicula ut eros nec, ornare ullamcorper tellus. Vestibulum vitae justo a nisi porta auctor. Donec at mi non ex posuere vulputate. Donec in lorem in dolor pharetra elementum vel et ante. Sed interdum tincidunt leo, id imperdiet felis suscipit at. Curabitur in rutrum lectus. Mauris nibh mauris, imperdiet in faucibus ut, vulputate nec orci.',
  '<p>Sed volutpat libero ac velit sollicitudin lacinia. Proin justo diam, ullamcorper at sagittis vitae, suscipit id nunc. Integer tincidunt varius justo. Suspendisse accumsan sapien at tincidunt venenatis. Nam non ligula ligula. Maecenas vel dui efficitur, dictum turpis eu, iaculis odio. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam iaculis sollicitudin turpis, vel scelerisque ante varius in. Nulla porttitor tempus magna. Suspendisse ac pretium dui, ac dapibus massa. Aliquam in egestas arcu, a consectetur ipsum. Mauris vitae tellus ut neque mollis rutrum. Nulla placerat fermentum quam, sed viverra enim volutpat nec. Fusce tincidunt tempus mauris, nec imperdiet erat luctus vitae. Quisque hendrerit quis purus nec sodalesz</p>
  <p>Praesent facilisis quis dui non iaculis. Sed ut odio vitae odio maximus convallis ac ut orci. Nam vel leo vehicula, pretium magna quis, rutrum dui. Donec mollis eleifend nunc in lacinia. Donec feugiat gravida ex, consectetur imperdiet tellus lacinia at. Vestibulum maximus erat odio, ut sagittis ipsum varius convallis. Nam pulvinar odio odio, in rhoncus lorem egestas ultricies. Proin faucibus diam vel sagittis facilisis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tincidunt nulla vel odio iaculis aliquet. Cras eget efficitur sapien. Duis aliquet id nunc at imperdiet. Proin ut rutrum justo. Duis dui neque, tristique eu luctus in, volutpat at dolor.</p>
  <p>Ut efficitur nunc eget laoreet feugiat. Nunc mattis eleifend risus, eget placerat magna dictum ac. Morbi volutpat fringilla ex, non varius ante interdum ac. Vivamus vitae ante sit amet nunc facilisis tempus. Praesent rutrum euismod mi, et elementum purus gravida id. Sed placerat rhoncus interdum. Nunc vel nisi non tortor finibus imperdiet. Aliquam erat volutpat. Sed commodo velit lorem, id pulvinar ipsum dignissim non. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce vitae nisi nec erat sodales luctus ut vitae felis. Quisque id lacinia lacus. In vehicula libero enim, et ullamcorper justo commodo et. Cras blandit sodales ultricies.</p>
  <p>Aliquam erat volutpat. Aenean sed gravida purus. Donec egestas massa at diam tempus faucibus. Phasellus id neque suscipit, luctus dolor id, vestibulum lorem. Integer dignissim sem sed arcu maximus pulvinar. Vivamus ultrices viverra efficitur. Mauris vitae dignissim ante, sed tincidunt neque. Curabitur mattis mollis pellentesque.</p>',
  '2015-06-11 14:30'
),
(
  'Curabitur porttitor bibendum semper',
  'Nulla iaculis gravida hendrerit. Ut auctor rhoncus turpis, id elementum purus scelerisque ac. Aenean semper nunc et elit egestas, placerat consequat tortor finibus. Curabitur turpis dui, malesuada quis dolor sit amet, aliquam cursus turpis. Proin et quam non metus mollis tincidunt eu at justo.',
  '<p>Sed volutpat libero ac velit sollicitudin lacinia. Proin justo diam, ullamcorper at sagittis vitae, suscipit id nunc. Integer tincidunt varius justo. Suspendisse accumsan sapien at tincidunt venenatis. Nam non ligula ligula. Maecenas vel dui efficitur, dictum turpis eu, iaculis odio. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam iaculis sollicitudin turpis, vel scelerisque ante varius in. Nulla porttitor tempus magna. Suspendisse ac pretium dui, ac dapibus massa. Aliquam in egestas arcu, a consectetur ipsum. Mauris vitae tellus ut neque mollis rutrum. Nulla placerat fermentum quam, sed viverra enim volutpat nec. Fusce tincidunt tempus mauris, nec imperdiet erat luctus vitae. Quisque hendrerit quis purus nec sodalesz</p>
  <p>Praesent facilisis quis dui non iaculis. Sed ut odio vitae odio maximus convallis ac ut orci. Nam vel leo vehicula, pretium magna quis, rutrum dui. Donec mollis eleifend nunc in lacinia. Donec feugiat gravida ex, consectetur imperdiet tellus lacinia at. Vestibulum maximus erat odio, ut sagittis ipsum varius convallis. Nam pulvinar odio odio, in rhoncus lorem egestas ultricies. Proin faucibus diam vel sagittis facilisis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tincidunt nulla vel odio iaculis aliquet. Cras eget efficitur sapien. Duis aliquet id nunc at imperdiet. Proin ut rutrum justo. Duis dui neque, tristique eu luctus in, volutpat at dolor.</p>
  <p>Ut efficitur nunc eget laoreet feugiat. Nunc mattis eleifend risus, eget placerat magna dictum ac. Morbi volutpat fringilla ex, non varius ante interdum ac. Vivamus vitae ante sit amet nunc facilisis tempus. Praesent rutrum euismod mi, et elementum purus gravida id. Sed placerat rhoncus interdum. Nunc vel nisi non tortor finibus imperdiet. Aliquam erat volutpat. Sed commodo velit lorem, id pulvinar ipsum dignissim non. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce vitae nisi nec erat sodales luctus ut vitae felis. Quisque id lacinia lacus. In vehicula libero enim, et ullamcorper justo commodo et. Cras blandit sodales ultricies.</p>
  <p>Aliquam erat volutpat. Aenean sed gravida purus. Donec egestas massa at diam tempus faucibus. Phasellus id neque suscipit, luctus dolor id, vestibulum lorem. Integer dignissim sem sed arcu maximus pulvinar. Vivamus ultrices viverra efficitur. Mauris vitae dignissim ante, sed tincidunt neque. Curabitur mattis mollis pellentesque.</p>',
  '2015-06-12 15:30'
),
(
  'Pellentesque habitant morbi tristique senectus et netus',
  'Proin faucibus diam orci, id sollicitudin dui porttitor nec. Duis sollicitudin turpis a interdum convallis. Aenean egestas faucibus cursus. Sed eros purus, consequat sed tristique sed, bibendum eget arcu. Nam eu lacus mollis, suscipit erat eget, imperdiet ligula. Integer justo turpis, scelerisque nec ligula at, luctus efficitur ante.',
  '<p>Sed volutpat libero ac velit sollicitudin lacinia. Proin justo diam, ullamcorper at sagittis vitae, suscipit id nunc. Integer tincidunt varius justo. Suspendisse accumsan sapien at tincidunt venenatis. Nam non ligula ligula. Maecenas vel dui efficitur, dictum turpis eu, iaculis odio. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam iaculis sollicitudin turpis, vel scelerisque ante varius in. Nulla porttitor tempus magna. Suspendisse ac pretium dui, ac dapibus massa. Aliquam in egestas arcu, a consectetur ipsum. Mauris vitae tellus ut neque mollis rutrum. Nulla placerat fermentum quam, sed viverra enim volutpat nec. Fusce tincidunt tempus mauris, nec imperdiet erat luctus vitae. Quisque hendrerit quis purus nec sodalesz</p>
  <p>Praesent facilisis quis dui non iaculis. Sed ut odio vitae odio maximus convallis ac ut orci. Nam vel leo vehicula, pretium magna quis, rutrum dui. Donec mollis eleifend nunc in lacinia. Donec feugiat gravida ex, consectetur imperdiet tellus lacinia at. Vestibulum maximus erat odio, ut sagittis ipsum varius convallis. Nam pulvinar odio odio, in rhoncus lorem egestas ultricies. Proin faucibus diam vel sagittis facilisis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tincidunt nulla vel odio iaculis aliquet. Cras eget efficitur sapien. Duis aliquet id nunc at imperdiet. Proin ut rutrum justo. Duis dui neque, tristique eu luctus in, volutpat at dolor.</p>
  <p>Ut efficitur nunc eget laoreet feugiat. Nunc mattis eleifend risus, eget placerat magna dictum ac. Morbi volutpat fringilla ex, non varius ante interdum ac. Vivamus vitae ante sit amet nunc facilisis tempus. Praesent rutrum euismod mi, et elementum purus gravida id. Sed placerat rhoncus interdum. Nunc vel nisi non tortor finibus imperdiet. Aliquam erat volutpat. Sed commodo velit lorem, id pulvinar ipsum dignissim non. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce vitae nisi nec erat sodales luctus ut vitae felis. Quisque id lacinia lacus. In vehicula libero enim, et ullamcorper justo commodo et. Cras blandit sodales ultricies.</p>
  <p>Aliquam erat volutpat. Aenean sed gravida purus. Donec egestas massa at diam tempus faucibus. Phasellus id neque suscipit, luctus dolor id, vestibulum lorem. Integer dignissim sem sed arcu maximus pulvinar. Vivamus ultrices viverra efficitur. Mauris vitae dignissim ante, sed tincidunt neque. Curabitur mattis mollis pellentesque.</p>',
  '2015-06-13 16:30'
);
