<?php if ($pager['total_pages'] > 1) : ?>
<nav>
    <ul class="pagination pagination-lg">
        <li<?=(($pager['current'] == 1) ? ' class="disabled"' : '')?>>
            <a href="?page=<?=$pager['before']?>" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
<?php for ($i = 1; $i < $pager['total_pages'] + 1; $i++) : ?>
<?php if (($i <= $pager['current']+3) && ($i >= $pager['current']-3)) : ?>
        <li<?=(($pager['current'] == $i) ? ' class="active"' : '')?>>
            <a href="?page=<?=$i?>">
                <?=$i?>
            </a>
        </li>
<?php endif; ?>
<?php endfor; ?>
        <li<?=(($pager['current'] == $pager['last']) ? ' class="disabled"' : '')?>>
            <a href="?page=<?=$pager['next']?>" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>
<?php endif; ?>
