<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('https://farm6.staticflickr.com/5178/5451787468_115a55fb5f_o.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-heading">

                </div>
            </div>
        </div>
    </div>
</header>

<?=$this->getContent()?>
